version: '3'

services:
    mysql-luizalabs:
        image: gustavocarvalhoti/luizalabs-db:3
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
        volumes:
            - mysql.luizalabs:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - mysql-db

    luizalabs-api:
        image: gustavocarvalhoti/luizalabs-api:1
        environment:
            QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-luizalabs:3306/luizalabs?autoReconnect=true
        networks:
            - mysql-db
        ports:
            - 8080:8080
        depends_on:
            - mysql-luizalabs
        restart: always

networks:
    mysql-db:
        driver: bridge

volumes:
    mysql.luizalabs: